version: 1
root:
  level: DEBUG
  handlers:
    - console
    - file
formatters:
  standard:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
handlers:
  console:
    class : logging.StreamHandler
    formatter: standard
    level   : INFO
  file:
    class : logging.FileHandler
    level : DEBUG
    formatter: standard
    filename: dex.log
